missing-people/Controllers/MissingPersonController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using missing_people.Models;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using NpgsqlTypes;
using Microsoft.AspNetCore.Authorization;

namespace missing_people.Controllers
{
    public class MissingPersonController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public MissingPersonController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int gender)
        {
            List<MissingPerson> missingPersonList;

            if (gender == 1)
            {
                missingPersonList = await _context.MissingPeople
                    .Where(x => x.Gender == "Male")
                    .ToListAsync();
            }
            else if (gender == 2)
            {
                missingPersonList = await _context.MissingPeople
                    .Where(x => x.Gender == "Female")
                    .ToListAsync();
            }
            else missingPersonList = await _context.MissingPeople.ToListAsync();

            return View(missingPersonList);
        }


        public async Task<IActionResult> Details(int id)
        {
            var missingPerson = await _context.MissingPeople.FindAsync(id);
            return View(missingPerson);
        }

        [Authorize(Roles = "admin,user")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "admin,user")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Description,ImageUrl,DateLastSeen,LocationLastSeen,ContactName,ContactEmail,UserId,Gender")] MissingPerson person)
        {
            if (person.Gender == "0")
            {
                person.Gender = "Male";
            }
            else { person.Gender = "Female"; }

            person.DateLastSeen = person.DateLastSeen.ToUniversalTime();


            _context.MissingPeople.Add(person);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var missingPerson = await _context.MissingPeople.FindAsync(id);
            return View(missingPerson);
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,FirstName,LastName,Description,ImageUrl,DateLastSeen,LocationLastSeen,ContactName,ContactEmail,UserId,Gender")] MissingPerson person)
        {
            var editedMissingPerson = new MissingPerson
            {
                Id = person.Id,
                FirstName = person.FirstName,
                LastName = person.LastName,
                Description = person.Description,
                ImageUrl = person.ImageUrl,
                DateLastSeen = person.DateLastSeen.ToUniversalTime(),
                LocationLastSeen = person.LocationLastSeen,
                ContactName = person.ContactName,
                ContactEmail = person.ContactEmail,
                Gender = person.Gender
            };
            if (person.Gender == "0")
            {
                editedMissingPerson.Gender = "Male";
            }
            else editedMissingPerson.Gender = "Female";

            _context.Update(editedMissingPerson);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var missingPerson = await _context.MissingPeople.FindAsync(id);
            return View(missingPerson);
        }

        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var person = await _context.MissingPeople.FindAsync(id);
            _context.MissingPeople.Remove(person);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MissingPersonExists(Guid id)
        {
            return _context.MissingPeople.Any();
        }
    }
}

missing-people/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - missing_people</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/missing_people.styles.css" asp-append-version="true" />
    <link href="~/css/output.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="MissingPerson" asp-action="Index">missing_people</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Piotr Bialobrzeski
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>